### ISSUE TITLE
Question: Which is the best way to avoid downloading gradlew on every run?

### ISSUE THREAD

**Issue by Macarse** [alvr/alpine-android#2]
Hey, I just started testing this docker image and it's working perfectly.

I would like to hear your opinion on how to avoid downloading gradlew and mvn dependencies on every build.

Thanks!

**Comment by alvr** [comment]
This docker container doesn't include gradle because the recommended action is to use the wrapper the project includes.

To avoid download gradle and the project dependencies every run, some CI includes a configuration to cache directories. The directories to cache are:

- $HOME/.gradle/caches/
- $HOME/.gradle/wrapper/

**Comment by Macarse** [comment]
@alvr no worries. 
That's what I ended up doing. Storing `~/.gradle` in a S3 bucket.
 Thanks!
