### ISSUE TITLE
Image with JDK 11 and JDK 17 at the same time

### ISSUE THREAD

**Issue by BugsBunnyBR** [alvr/alpine-android#24]
I am in a weird situation where AGP 8.0 needs JDK 17, but I need to configure Kotlins `jvmToolChain` to 11. Do you think it would be possible?

**Comment by alvr** [comment]
Hi. Yes is totally possible. In my personal project, the CI is [using Java 17](https://github.com/alvr/katana/blob/develop/.github/actions/common-steps/action.yml) because of AGP 8, but the toolchain is using Java 11.

[Here](https://github.com/alvr/katana/blob/develop/build-logic/common/src/main/kotlin/dev/alvr/katana/buildlogic/KatanaConfiguration.kt#L16-L18) is the Java version used for the project, and [here](https://github.com/alvr/katana/blob/develop/build-logic/common/src/main/kotlin/dev/alvr/katana/buildlogic/extensions.kt#L57-L94) are the configuration for the tasks and extensions to use that version.

**Comment by BugsBunnyBR** [comment]
Ohh nice, thanks. I think I understand it now, you set the `jvmToolChain` and still had to make all kotlin tasks use that `jvmTarget`. So we don't need to JDKs installed in the machine.
