### ISSUE TITLE
javax.xml.bind.JAXBException

### ISSUE THREAD

**Issue by TomorrowAndroid** [alvr/alpine-android#6]
Since the update yesterday none of our pipelines run anymore.

```
Caused by: java.util.ServiceConfigurationError: javax.annotation.processing.Processor: android.databinding.annotationprocessor.ProcessDataBinding Unable to get public no-arg constructor
4649 	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1200)
4650 	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1233)
4651 	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1224)
4652 	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.doLoadProcessors(ProcessorLoader.kt:80)
4653 	at org.jetbrains.kotlin.kapt3.base.ProcessorLoader.loadProcessors(ProcessorLoader.kt:45)
4654 	at org.jetbrains.kotlin.kapt3.base.Kapt.kapt(Kapt.kt:42)
4655 	... 29 more
4656 Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
4657 	... 35 more
4658 Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
4659 	... 35 more
```

I think it's related to the jdk11 update.
How can we fix this or can you provide an image with the old jdk?

**Comment by Sserra90** [comment]
I can confirm this. It seems it's related with jdk11, builds are failing now.
Can you revert or provide an image with an older jdk ?

**Comment by TomorrowAndroid** [comment]
We created an internal custom docker image now with jdk8. :)
So this is resolved from our side.

**Comment by Sserra90** [comment]
Same here to workaround the issue for now.

**Comment by alvr** [comment]
Hello @TomorrowAndroid and @Sserra90, sorry for the late reply. I upgraded to JDK11 because `apksigner` of the build-tools of Android R will require Java 9 or greater.

I reverted to JDK8 and I will make new images with JDK11 alongside with JDK8.

This error happened becase JAXB APIs were remove in JDK9, so the only solution to this is to add
```
implementation "jakarta.xml.bind:jakarta.xml.bind-api:2.3.3"
implementation "org.glassfish.jaxb:jaxb-runtime:2.3.3"
```

I will make a note so people who wants to sign their APKs, targeting Android R and using databinding should add those dependencies.
