### ISSUE TITLE
Android Gradle Plugin 7.0 will require Java 11

### ISSUE THREAD

**Issue by lbg-reggar** [alvr/alpine-android#7]
As per https://android-developers.googleblog.com/2020/12/announcing-android-gradle-plugin.html AGP 7.0.0 will require JDK 11. I noted that you upgraded to JDK11 and then downgraded again.

May be worth having a JDK11 version of this project?

**Comment by alvr** [comment]
Hello @lbg-reggar, I'll try to have a version for this holidays. 

The problem with the downgrade (812f89f) is that projects using DataBinding had #6 because JAXB was deleted from JDK in version 11. This new version of AGP [appears to include](https://mvnrepository.com/artifact/androidx.databinding/databinding-compiler/7.0.0-alpha03) `org.glassfish.jaxb:jaxb-runtime` so this doesn't seem to be a problem with this version, but this problem will continue for those who will still use AGP 4.x.

**Comment by alvr** [comment]
Hi @lbg-reggar I added the corresponding tags for the JDK11 version in de25a99.

Checkout the [new tags](https://github.com/alvr/alpine-android#tagging) available.
